import { App, Editor, MarkdownView, Modal, Notice, Plugin, PluginSettingTab, ButtonComponent, Setting, debounce } from 'obsidian';

export interface IconAttrSetting {
	entry: string;
	image: string;
}

interface MetadataIconSettings {
	enableSnippet: boolean;
	propertiesVisible: string;
	propertiesInvisible: string;
	IconAttrList: Array<IconAttrSetting>;
}

const DEFAULT_SETTINGS: MetadataIconSettings = {
	enableSnippet: true,
	propertiesVisible: "",
	propertiesInvisible: "",
	IconAttrList: [],
}

export default class MetadataIcon extends Plugin {
	settings: MetadataIconSettings;

	async onload() {
		await this.loadSettings();
		this.addSettingTab(new MetadataHiderSettingTab(this.app, this));
	}

	onunload() { }

	async loadSettings() {
		this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
	}

	async saveSettings() {
		await this.saveData(this.settings);
		await genSnippetCSS(this);
	}
}

function genEntryCSS(s: IconAttrSetting): string {
	const selector = `data-property-key="${s.entry}"`;
	let body: string[] = [
		`.metadata-property[${selector}] .metadata-property-key::after {`,
		`	content: "";`,
		`	background-image: url("${s.image}");`,
		`	background-size: 20px;`,
		`	width: 20px;`,
		`	height: 20px;`,
		`	position: absolute;`,
		`	left: 3px;`,
		`	top: 6px;`,
		`	z-index: -100;`,
		`	opacity: 0.5;`,
		`	background-repeat: no-repeat;`,
		`}`,
		`.metadata-property[${selector}] svg {`,
		`	visibility: hidden;`,
		`}`,
		``,
	]
	return body.join('\n');
}

async function genSnippetCSS(plugin: MetadataIcon) {
	const content: string[] = [
		"/* * WARNING: This file will be overwritten by plugin `Metadata Icon`.",
		"   * DO NOT EDIT THIS FILE DIRECTLY!!!",
		"   * Do not edit this file directly!!!",
		"*/",
		"",
		".setting-item-description:has(.metadata-icon-preview) {",
		"	display: flex;",
		"	align-items: center;",
		"	justify-content: space-around;",
		"}",
		"",
	];

	plugin.settings.IconAttrList.forEach((iconSetting, index) => {
		content.push(genEntryCSS(iconSetting));
	})

	const vault = plugin.app.vault;
	const path = `${plugin.manifest.dir}/styles.css`;
	if (await vault.adapter.exists(path)) { await vault.adapter.remove(path) }
	await plugin.app.vault.create(path, content.join('\n'));

	// Ensure Style Settings reads changes
	plugin.app.workspace.trigger("parse-style-settings");
}


class MetadataHiderSettingTab extends PluginSettingTab {
	plugin: MetadataIcon;
	debouncedGenerate: Function;

	constructor(app: App, plugin: MetadataIcon) {
		super(app, plugin);
		this.plugin = plugin;
		this.debouncedGenerate = debounce(this.generateSnippet, 1000, true);
		// Generate CSS immediately rather than 1 second - feels laggy
		this.generateSnippet();
	}

	async generateSnippet() {
		await genSnippetCSS(this.plugin);
	}

	display(): void {
		const { containerEl } = this;

		containerEl.empty();

		new Setting(containerEl)
			.setName("Add custom entry icon")
			.setDesc("Input entry name and icon url.")
			.addButton((button: ButtonComponent) => {
				button.setTooltip("Add new request")
					.setButtonText("+")
					.setCta().onClick(async () => {
						this.plugin.settings.IconAttrList.push({
							entry: "",
							image: "",
						});
						await this.plugin.saveSettings();
						this.display();
					});
			})
		this.plugin.settings.IconAttrList.forEach((iconSetting, index) => {
			const s = new Setting(this.containerEl)
				.then((setting) => {
					let span = setting.descEl.createEl("span", { text: "icon preview:" });
					span.setAttribute("style", `margin-right: 2px; `);
					let img = setting.descEl.createEl("img", { cls: "metadata-icon-preview" });
					img.setAttribute("src", iconSetting.image);
					img.setAttribute("width", `20px`);
				})
				.addSearch((cb) => {
					cb.setPlaceholder("entry name")
						.setValue(iconSetting.entry)
						.onChange(async (newValue) => {
							this.plugin.settings.IconAttrList[index].entry = newValue;
							await this.plugin.saveSettings();
						});
				})
				.addSearch((cb) => {
					cb.setPlaceholder("image url")
						.setValue(iconSetting.image)
						.onChange(async (newValue) => {
							this.plugin.settings.IconAttrList[index].image = newValue;
							await this.plugin.saveSettings();
						});
				})
				.addExtraButton((cb) => {
					cb.setIcon("cross")
						.setTooltip("Delete")
						.onClick(async () => {
							this.plugin.settings.IconAttrList.splice(index, 1);
							await this.plugin.saveSettings();
							this.display();
						});
				});
		});

		new Setting(containerEl)
			.setName("Force Refresh CSS")
			.addButton((button: ButtonComponent) => {
				button.setTooltip("Add new request")
					.setButtonText("Refresh")
					.setCta().onClick(async () => {
						// @ts-ignore
						const plugins = this.plugin.app.plugins;
						await plugins.disablePlugin(this.plugin.manifest.id);
						await plugins.enablePlugin(this.plugin.manifest.id);
					});
			})
	}
}
